services:
  #################################################
  # 서비스 1: 분석가용 개발 환경 : streamlit-dev
  #################################################
  streamlit-dev:
    container_name: streamlit_dev_env
    build:
      context: . # context를 프로젝트 루트로 변경
      dockerfile: ./docker/analyst_workspace/Dockerfile.dev
    volumes:
      # src 폴더를 컨테이너의 /app 폴더와 실시간 동기화
      - ./src:/app
    ports:
      - "8888:8888" # JupyterLab 포트
      - "8501:8501" # 개발 중 Streamlit 테스트용 포트
    env_file:
      - .env

  #########################################################
  # 서비스 2: 사용자용 대시보드 (프로덕션) : streamlit-prod
  #########################################################
  streamlit-prod:
    container_name: streamlit_prod_app
    build:
      context: . # context를 프로젝트 루트로 변경
      dockerfile: ./docker/dashboard_frequent_franchisee/Dockerfile.prod
    ports:
      - "8502:8501" # 개발용과 다른 포트 사용
    env_file:
      - .env
    volumes:
      # 로컬 src 폴더와 컨테이너 /app 폴더를 실시간 동기화하여 코드 변경 즉시 반영
      - ./src:/app
